### ISSUE TITLE
TimeoutError: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by feibi8597** [tungs/timecut#38]
TimeoutError: Navigation timeout of 30000 ms exceeded
    at D:\timecut_demo\node_modules\puppeteer\lib\LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (D:\timecut_demo\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (D:\timecut_demo\node_modules\puppeteer\lib\Page.js:672:49)
    at Page.<anonymous> (D:\timecut_demo\node_modules\puppeteer\lib\helper.js:112:23)
    at D:\timecut_demo\node_modules\timesnap\index.js:173:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by christianhujer** [comment]
I'm encountering the same error on Linux, but only if the SVG is "slow".

**Comment by tungs** [comment]
Hi all, could you post a sample web page that has this problem? Also, if you could verify that the page correctly loads in puppeteer, that would be helpful too to determine that timesnap/timecut has the problem. Thanks!

**Comment by christianhujer** [comment]
I'm experiencing the problem with the following SVG (in a Zip file because GitHub doesn't support uploading SVG files).

[GlowingLogo.zip](https://github.com/tungs/timecut/files/5323411/GlowingLogo.zip)

**Comment by feibi8597** [comment]
> Hi all, could you post a sample web page that has this problem? Also, if you could verify that the page correctly loads in puppeteer, that would be helpful too to determine that timesnap/timecut has the problem. Thanks!

I'm experiencing the problem with the following webpage，this webpage can correctly loads in puppeteer.
[timecut_demo.zip](https://github.com/tungs/timecut/files/5363727/timecut_demo.zip)

**Comment by tungs** [comment]
@feibi8597 it seems like the issue arises in timesnap from https://github.com/tungs/timesnap/blob/fdfece3dd7eb7766365b42a7ab3d4b94195d9a3f/index.js#L175 which uses `{ waitUntil: 'networkidle0' }`. Interestingly, it looks like if puppeteer tries to load the page with the same option, it can successfully load the page, so it seems like the time handling code in timesnap is interfering with completely loading the page.

If you need a solution now, you can fork `timesnap` and remove `{ waitUntil: 'networkidle0' }`, though you may want to use `--start-delay` / `startDelay` to pause a bit so the first frame gets loaded. Then you'd have to either install your forked version of timesnap into a forked version of timecut or you can just use timesnap and ffmpeg to make a video from the saved images.

In the long term, I'll add overwriting the hardcoded `{waitUntil: 'networkidle0'}`, as a feature request.

I did manage to get it to run-- it looks like you want to add custom styles to hide/disable the blinking cursor.

**Comment by tungs** [comment]
@christianhujer I tried to use your file with `timecut` and did produce a video-- albeit at a different speed, which isn't surprising, since svg is not supported. Can you verify that you are trying to capture just the svg, and not a webpage that embeds the svg?
