### ISSUE TITLE
[BUG] Randomly Fails to Execute

### ISSUE THREAD

**Issue by gurugeek** [tungs/timecut#65]
**Describe the bug**
It randomly fails to execute 

**To Reproduce**

 timecut/cli.js flow5.svg --viewport="520,520" --fps=30 --duration=10 \
  --frame-cache --pix-fmt=yuv420p --output=Flow5.mp4

**Expected behavior**
No Errors 

**Attachments and Screenshots**
Capturing Frame 47 to /Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut-temp-1654507450971/image-000000047.png...
Received signal 11 SEGV_MAPERR 000000000000
 [0x00011b210d79]
 [0x00011b140003]
 [0x00011b210c91]
 [0x7ff809fbadfd]
 [0x000000000000]
 [0x7ff809fa0f70]
[end of stack trace]
Error: Protocol error (Page.captureScreenshot): Target closed.
    at /Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/puppeteer/lib/Connection.js:182:12)
    at Page._screenshotTask (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/puppeteer/lib/Page.js:948:39)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
  -- ASYNC --
    at Page.<anonymous> (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.capture (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/timesnap/lib/capture-screenshot.js:93:31)
    at run (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/timesnap/index.js:271:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/timesnap/index.js:287:5)
    at async module.exports (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/index.js:210:7)
Error: Protocol error (Page.captureScreenshot): Target closed.
    at /Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/puppeteer/lib/Connection.js:182:12)
    at Page._screenshotTask (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/puppeteer/lib/Page.js:948:39)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
  -- ASYNC --
    at Page.<anonymous> (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.capture (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/timesnap/lib/capture-screenshot.js:93:31)
    at run (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/timesnap/index.js:271:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/timesnap/index.js:287:5)
    at async module.exports (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/index.js:210:7)
(node:88556) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.captureScreenshot): Target closed.
    at /Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/puppeteer/lib/Connection.js:182:12)
    at Page._screenshotTask (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/puppeteer/lib/Page.js:948:39)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
  -- ASYNC --
    at Page.<anonymous> (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.capture (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/timesnap/lib/capture-screenshot.js:93:31)
    at run (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/timesnap/index.js:271:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/node_modules/timesnap/index.js:287:5)
    at async module.exports (/Users/gurugeek/Documents/Dokumente - David’s iMac/fishdraw-main/timecut/index.js:210:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:88556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:88556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
gurugeek@davids-imac fishdraw-main % timecut/cli.js flow5.svg --viewport="520,520" --fps=30 --duration=10 \
  --frame-cache --pix-fmt=yuv420p --output=Flow5.mp4

**Desktop (please complete the following information):**
 - OS: MacOS Monterrey 
 - Node Version 14.17.0
 - Timecut Version 0.3.3

**Additional context**

**Comment by atulmy** [comment]
Facing this issue as well. @gurugeek did you manage to fix?

**Comment by tungs** [comment]
Just to confirm, are you trying to capture an animated svg? Animated svgs aren't supported currently by timeweb/timesnap/timecut
